### ISSUE TITLE
Cannot bootstrap SLE Micro 5.2

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/sumaform#1140]
Step to reproduce:

I added this to my `main.tf` : 
```
module "min-slemicro52" {
  source = "./modules/minion"
  base_configuration = module.base_core.configuration
  name = "min-slemicro52"
  image = "slemicro52-ign"
  server_configuration = module.uyuni.configuration
  auto_connect_to_master = false
  use_os_unreleased_updates = false
  use_os_released_updates = false
}
```

Then I follow the steps for bootstrapping from CLI. When I run `systemctl restart salt-minion.service` it fails with:
```
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]: Traceback (most recent call last):
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]:   File "/usr/bin/evil-minions", line 20, in <module>
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]:     from evilminions.hydra import Hydra
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]:   File "/usr/lib/python3.6/site-packages/evilminions/hydra.py", line 19, in <module>
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]:     salt.log.mixins.LoggingTraceMixIn.trace = lambda self, msg, *args, **kwargs: None
Aug 09 10:14:36 min-slemicro52 evil-minions[2542]: AttributeError: module 'salt.log' has no attribute 'mixins'
Aug 09 10:14:36 min-slemicro52 systemd[1]: salt-minion.service: Main process exited, code=exited, status=1/FAILURE
```

So it seems some dependency issue on evil minions, although I didn't activate it. 

Workaround:
I removed `/etc/systemd/system/salt-minion.service.d/override.conf` which contains some evil minion configuration and rebooted, and now everything is working as expected

**Comment by aaannz** [comment]
Interesting, evil-minions package is installed in kiwi template so they are available for testing if needed, but I did not expect it to be running automatically. I will remove it from kiwi template.

**Comment by mbussolotto** [comment]
for the sake of clarity, this is the content of `/etc/systemd/system/salt-minion.service.d/override.conf`
```
[Service]

# change the salt-minion executable with evil-minions
#
# for a full list of commandline switches use `evil-minions --help`
#
ExecStart=
ExecStart=/usr/bin/evil-minions --count=10 --ramp-up-delay=0 --slowdown-factor=0.0

# allow for more generous limits as evil-minion is descriptor-intensive
LimitNOFILE=infinity
TasksMax=infinity

# kill subprocesses when stopping this service
KillMode=control-group
```

**Comment by aaannz** [comment]
Updated kiwi template and disabled installing evil minions by default. Should work now.
