### ISSUE TITLE
salt-call: command not found on centos8o

### ISSUE THREAD

**Issue by ktsamis** [uyuni-project/sumaform#763]
main.tf:
```
module "base" {
  source = "./modules/base"

  cc_username = ""
  cc_password = ""

  use_avahi = false
  name_prefix = "" // if you use name_prefix, make sure to update the server_configuration for clients/minions below
  images      = [ "centos8o", "centos6o", "ubuntu1604o", "ubuntu2004o" ]
  provider_settings = {
    bridge = "br0"
    pool = "default"
    network_name = "" // change to "" if you change bridge below
    additional_network = null
  }
}

module "centos8o" {
  source = "./modules/host"
  base_configuration = "${module.base.configuration}"
  quantity = 2
  name = "centos8o"
  image = "centos8o"
}
```
relevant output from terraform apply:
```
module.centos8o.module.host.null_resource.provisioning[1]: Provisioning with 'remote-exec'...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Connecting to remote host via SSH...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   Host: 10.161.228.132
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   User: root
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   Password: true
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   Private key: false
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   Certificate: false
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   SSH Agent: false
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   Checking Host Key: false
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Connected!
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[0]: Still creating... [20s elapsed]
module.centos8o.module.host.null_resource.provisioning[1]: Still creating... [20s elapsed]
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
module.centos6o.module.host.libvirt_domain.domain[1]: Still creating... [50s elapsed]
module.centos6o.module.host.libvirt_domain.domain[0]: Still creating... [50s elapsed]
module.ubuntu2004o.module.host.libvirt_domain.domain[1]: Still creating... [50s elapsed]
module.ubuntu2004o.module.host.libvirt_domain.domain[0]: Still creating... [50s elapsed]
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
module.ubuntu1604o.module.host.libvirt_domain.domain[0]: Still creating... [50s elapsed]
module.ubuntu1604o.module.host.libvirt_domain.domain[1]: Still creating... [50s elapsed]
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[0]: Still creating... [30s elapsed]
module.centos8o.module.host.null_resource.provisioning[1]: Still creating... [30s elapsed]
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
module.ubuntu1604o.module.host.libvirt_domain.domain[1]: Creation complete after 58s [id=0404b61c-3ff3-4ae6-86e7-465266779cb6]
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...
```

**Comment by moio** [comment]
Please log into the machine via `virsh console` on its host and inspect it, in particular `cloud-init` log files in `/var/log` (if you can't make sense of them, of course feel free to paste them here).

Evidently installation of salt (which is something we expect `cloud-init` to do) has failed, so our script keeps waiting forever.

So the next question is: why? It could be a bug as well as something else (eg. network problem, repos unavailable and so on).

**Comment by ktsamis** [comment]
```module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found                                                                         
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...                                                                                                       
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Traceback (most recent call last):                                                                                                        
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec):   File "/usr/bin/salt-call", line 7, in <module>                                                                                          
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec):     from salt.scripts import salt_call                                                                                                    
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): ModuleNotFoundError: No module named 'salt.scripts'                                                                                       
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Waiting for salt to be installed...                                                                                                       
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Traceback (most recent call last):                                                                                                        
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):   File "/usr/bin/salt-call", line 7, in <module>                                                                                          
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec):     from salt.scripts import salt_call                                                                                                    
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): ModuleNotFoundError: No module named 'salt'                                                                                               
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Waiting for salt to be installed...                                                                                                       
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): Usage: salt-call [options] <function> [arguments]                                                                                         
                                                                                                                                                                                                                   
module.centos8o.module.host.null_resource.provisioning[0] (remote-exec): salt-call: error: Requires function, --grains or --doc                                                                                    
module.centos8o.module.host.null_resource.provisioning[0]: Provisioning with 'file'...                                                                                                                             
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): Usage: salt-call [options] <function> [arguments]                                                                                         
                                                                                                                                                                                                                   
module.centos8o.module.host.null_resource.provisioning[1] (remote-exec): salt-call: error: Requires function, --grains or --doc                                                                                    
module.centos8o.module.host.null_resource.provisioning[1]: Provisioning with 'file'...                                                                                                                             
```
So after this error being there, the deployment actually completed with green salt states. I think this is a race condition, it didn't install salt in time before and failed, now it did and succeeded. I see in the cloud-init-output.log this:

```
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="IL" preference="15">http://rep-epel-il.upress.io/8/Eve
rything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="IL" preference="15">http' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="FR" preference="14">http://mirrors.ircam.fr/pub/fedora
/epel/8/Everything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="FR" preference="14">http' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="rsync" type="rsync" location="FR" preference="14">rsync://mirrors.ircam.fr/fedora-
epel/8/Everything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="rsync" type="rsync" location="FR" preference="14">rsync' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="SE" preference="13">http://mirrors.glesys.net/fedora/e
pel/8/Everything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="SE" preference="13">http' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="rsync" type="rsync" location="SE" preference="13">rsync://mirrors.glesys.net/fedor
a/epel/8/Everything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="rsync" type="rsync" location="SE" preference="13">rsync' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="IS" preference="12">http://fedora.nyherji.is/epel/8/Ev
erything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="IS" preference="12">http' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="rsync" type="rsync" location="UA" preference="11">rsync://epel.besthosting.ua/epel
/8/Everything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="rsync" type="rsync" location="UA" preference="11">rsync' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="UA" preference="11">http://epel.besthosting.ua/8/Every
thing/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="UA" preference="11">http' contains bad letter]
[MIRROR] nss-mdns-0.14.1-7.el8.x86_64.rpm: Curl error (3): URL using bad/illegal format or missing URL for http://<url protocol="http" type="http" location="BE" preference="10">http://mirror.kinamo.be/epel/8/Eve
rything/x86_64/repodata/repomd.xml</url>/Packages/n/nss-mdns-0.14.1-7.el8.x86_64.rpm [Host name '<url protocol="http" type="http" location="BE" preference="10">http' contains bad letter]
(13/13): nss-mdns-0.14.1-7.el8.x86_64.rpm       385 kB/s |  49 kB     00:00    
--------------------------------------------------------------------------------
Total                                           3.0 MB/s |  13 MB     00:04     
warning: /var/cache/dnf/BaseOS-8338398890a7e54c/packages/avahi-0.7-19.el8.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
CentOS-8 - Base                                 191 kB/s | 1.6 kB     00:00    
Importing GPG key 0x8483C65D:
 Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
 Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
Key imported successfully
``` 
which I think means that the installation was delayed because the mirror for actual centos 8 repo was not responding properly to the request and the nss-mdns package couldn't be installed so everything was delayed. I think since it now worked we can close this issue because even if it comes back again there's not much we can do about the centos mirror.

**Comment by moio** [comment]
There's a couple of things that we could do if this repeats: allow for more time in case it's needed, and in the very worst case hardcode the mirror's IP in a repo via cloud-init, so that nss-mdns and any other necessary package is taken from the mirror.

Chances are we will do that anyway.

Thanks for looking into this issue
